export const MentorsData = [
  {
    id: 1,
    name: "Folashade Temitope Williams",
    email: "f.williams@xyz.com",
    phone: "+7 (903) 941-02-27",
    level: "Admin",
    position: "Backend Engineer",
  },
  {
    id: 2,
    name: "John Doe",
    email: "j.doe@xyz.com",
    phone: "+1 (555) 555-1234",
    level: "Manager",
    position: "Project Manager",
  },
  {
    id: 3,
    name: "Jane Smith",
    email: "j.smith@xyz.com",
    phone: "+44 7900 123456",
    level: "Admin",
    position: "Frontend Developer",
  },
  {
    id: 4,
    name: "Michael Johnson",
    email: "m.johnson@xyz.com",
    phone: "+1 (777) 123-4567",
    level: "Senior",
    position: "UI/UX Designer",
  },
  {
    id: 5,
    name: "Sarah Lee",
    email: "s.lee@xyz.com",
    phone: "+44 7800 567890",
    level: "Junior",
    position: "Data Analyst",
  },
  {
    id: 6,
    name: "David Kim",
    email: "d.kim@xyz.com",
    phone: "+82 10-1234-5678",
    level: "Mid",
    position: "Software Engineer",
  },
  {
    id: 7,
    name: "Emily Brown",
    email: "e.brown@xyz.com",
    phone: "+1 (555) 789-0123",
    level: "Admin",
    position: "HR Specialist",
  },
  {
    id: 8,
    name: "Matthew Garcia",
    email: "m.garcia@xyz.com",
    phone: "+34 600 123 456",
    level: "Senior",
    position: "DevOps Engineer",
  },
  {
    id: 9,
    name: "Sophia Martinez",
    email: "s.martinez@xyz.com",
    phone: "+1 (333) 456-7890",
    level: "Mid",
    position: "Marketing Manager",
  },
  {
    id: 10,
    name: "Liam Thompson",
    email: "l.thompson@xyz.com",
    phone: "+44 7700 123456",
    level: "Manager",
    position: "Business Analyst",
  },
  {
    id: 11,
    name: "Olivia Rodriguez",
    email: "o.rodriguez@xyz.com",
    phone: "+1 (222) 987-6543",
    level: "Admin",
    position: "Operations Manager",
  },
  {
    id: 12,
    name: "William Davis",
    email: "w.davis@xyz.com",
    phone: "+1 (888) 654-3210",
    level: "Junior",
    position: "QA Engineer",
  },
];
