const countryCodes = [
  { name: "Nigeria", code: "+234" },
  { name: "United States", code: "+1" },
  { name: "United Kingdom", code: "+44" },
  { name: "India", code: "+91" },
  { name: "Canada", code: "+1" },
  { name: "Australia", code: "+61" },
  { name: "Germany", code: "+49" },
  { name: "France", code: "+33" },
  { name: "South Africa", code: "+27" },
  { name: "Brazil", code: "+55" },
  { name: "Mexico", code: "+52" },
  { name: "China", code: "+86" },
  { name: "Japan", code: "+81" },
  { name: "Russia", code: "+7" },
  { name: "Italy", code: "+39" },
  { name: "Spain", code: "+34" },
  { name: "Netherlands", code: "+31" },
  { name: "South Korea", code: "+82" },
  { name: "Argentina", code: "+54" },
  { name: "Egypt", code: "+20" },
  { name: "Turkey", code: "+90" },
  { name: "United Arab Emirates", code: "+971" },
  { name: "Sweden", code: "+46" },
  { name: "Switzerland", code: "+41" },
  { name: "Malaysia", code: "+60" },
  { name: "New Zealand", code: "+64" },
  { name: "Philippines", code: "+63" },
  { name: "Pakistan", code: "+92" },
  { name: "Bangladesh", code: "+880" },
  { name: "Saudi Arabia", code: "+966" },
  { name: "Indonesia", code: "+62" },
  { name: "Thailand", code: "+66" },
  { name: "Vietnam", code: "+84" },
  { name: "Kenya", code: "+254" },
  { name: "Israel", code: "+972" },
  { name: "Ghana", code: "+233" },
  { name: "Singapore", code: "+65" },
  { name: "Portugal", code: "+351" },
  { name: "Belgium", code: "+32" },
  { name: "Austria", code: "+43" },
  { name: "Denmark", code: "+45" },
  { name: "Norway", code: "+47" },
  { name: "Ireland", code: "+353" },
  { name: "Finland", code: "+358" },
  { name: "Greece", code: "+30" },
  { name: "Poland", code: "+48" },
  { name: "Chile", code: "+56" },
  { name: "Colombia", code: "+57" },
  { name: "Peru", code: "+51" },
  { name: "Venezuela", code: "+58" },
  { name: "Czech Republic", code: "+420" },
  { name: "Romania", code: "+40" },
  { name: "Hungary", code: "+36" },
  { name: "Ukraine", code: "+380" },
  { name: "Morocco", code: "+212" },
  { name: "Tunisia", code: "+216" },
  { name: "Qatar", code: "+974" },
  { name: "Kuwait", code: "+965" },
  { name: "Oman", code: "+968" },
  { name: "Jordan", code: "+962" },
];

export default countryCodes;
